### ISSUE TITLE
Mindtrick can be used even when there is no one near you.

### ISSUE THREAD

**Issue by Grab11** [TheSil/base_enhanced#100]
If you stand close in front of wall you can cast mindtrick even when there is no enemy around.

**Comment by deathsythe47** [comment]
I just checked this and it is indeed pretty weird. If you aim at the floor, or a nearby box/wall, you can cast mindtrick(on nobody) and waste some force points.

But if you aim at the sky or a far-away box/wall, you cannot cast mindtrick.

Now some people might argue "you should be able to cast it to prevent people from spamming mind trick." Whether or not that is true, regardless, the behavior should be the same for aiming at closeby things and aiming at far-away things.

Personally, I think it should NOT cast mind trick if there are no enemies around, regardless of aim.

**Comment by TheSil** [comment]
What mind trick level?

**Comment by deathsythe47** [comment]
I only tested it with mindtrick 3. Maybe different for others?

**Comment by deathsythe47** [comment]
Actually nm I tested it with 2 sorry. Maybe different for others.

**Comment by Grab11** [comment]
No, same problem with every level.

**Comment by TheSil** [comment]
It actually considered wall as a valid NPC and tried to mind trick it :)

**Comment by deathsythe47** [comment]
LOL
