### ISSUE TITLE
Bots jump around like crazy on maps without botroutes

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#101]
Add a bot to a map without botroutes (like most siege maps) and they jump around everywhere endlessly. Really annoying especially if you have cg_jumpsounds enabled.

**Comment by TheSil** [comment]
I think some mod had this fixed, japp, or maybe even OpenJK.

**Comment by NoahBennet** [comment]
Why to fix "bugs" like that, is there anyone playing against bots these days? For me it seems like a perfect opportunity to train my aim... One can host a homeserver with custom map, add bots and can train aim all day long. Also how would a fix like this look like? The bots would just stand still? (Hence no botrout they have no idea where to go..)

**Comment by deathsythe47** [comment]
Unless you regularly play against opponents who constantly jump everywhere(not strafing), you would get better aim practice by shooting bots that are using normal movement.

The bots should just run around toward enemies, basically same movement they already do, just without jumping.

**Comment by deathsythe47** [comment]
OJP might be a good resource for this. They had pretty complex AI for bots in siege, including attacking objectives, etc.

**Comment by deathsythe47** [comment]
https://github.com/deathsythe47/base_entranced/commit/124d2024712859d26c1b17fda2fd1e07cee070a9
