### ISSUE TITLE
Alternate fire mines use wrong kill message

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#102]
In mp_ingame.str, weapon kill messages are listed with primary first, and alternate second. For example, disruptor:

```
REFERENCE           KILLED_DISRUPTOR
NOTES               "Death message, disruptor"
LANG_ENGLISH        "was disrupted by"

REFERENCE           KILLED_DISRUPTORSNIPE
NOTES               "Death message, disruptor in sniping mode"
LANG_ENGLISH        "was sniped by"
```

Here is rocket launcher:

```
REFERENCE           KILLED_ROCKET
NOTES               "Death message, rocket"
LANG_ENGLISH        "was rocketed by"

REFERENCE           KILLED_ROCKET_HOMING
NOTES               "Death message, homing rocket"
LANG_ENGLISH        "was homed by"
```

Primary fire mines say "was tripped by" and that is correct because they are actual trip mines that you can trip over (they use a tripwire). However, alternate mines are supposed to use "was mined by" since they are not actually tripmines, but proximity/timed mines. Raven knew this and wrote in mp_ingame.str:

```
REFERENCE           KILLED_TRIPMINE
NOTES               "Death message, tripmine"
LANG_ENGLISH        "was tripped by"

REFERENCE           KILLED_TRIPMINE_TIMED
NOTES               "Death message, tripmine timed"
LANG_ENGLISH        "was mined by"
```

However some bug is causing alternate mines to trigger the "was tripped by" message anyway. For some reason alternate mines don't correctly use the "was mined by" string.

**Comment by deathsythe47** [comment]
Btw, I tested this and it is impossible to trigger "was mined by" even by using the mine life timer (put mine 1m away from low-hp enemy and wait for timer to expire)

it still says "was tripped by" even for timed explosion

**Comment by TheSil** [comment]
Yea it was not used by server game code at all. I guess this should be checked systematically, it is not first case of incorrect "method of death".

**Comment by deathsythe47** [comment]
Damn you are fast.

**Comment by TheSil** [comment]
And you have quite a lot of bugs at your disposal, how much more can I expect? :)

**Comment by deathsythe47** [comment]
I am the master of siege bugs

**Comment by TheSil** [comment]
Well i would say like half of these bugs are common to whole JKA, not just siege.

**Comment by Grab11** [comment]
Duo just doesn't have real life.

**Comment by TheSil** [comment]
Just do not over spam it here, i will be away for like 2 weeks soon, so I am kind of worried what will be here when i get back :D

**Comment by entdark** [comment]
Fix by your own and pull request.
