### ISSUE TITLE
Alert player if they have a different BSP than the server

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#109]
When updating maps, it is annoying/dumb to use different map names, like renaming the map to ffa_entsgonnarage_v1.3.bsp

It would be helpful if server could detect if client has a different BSP file from the server, and if so, notify them.

**Comment by dpadgett** [comment]
server cannot detect this kind of stuff.  client doesn't send its pk3 checksums to server, its the other way around.  it must be done by client.

**Comment by dpadgett** [comment]
ok so server might be able to detect it.  client sends over its pk3 checksums in CL_SendPureChecksums which seems to happen whether or not server is pure.  server could send a warning if the map pk3 checksum is different.

**Comment by TheSil** [comment]
I am already getting for example:

WARNING: You are missing some files referenced by the server:
base/test.pk3
base/base_enhanced.pk3

But that is not what you mean i guess. Anyway I think that this update is more for engine than for game code.
