### ISSUE TITLE
Aimbot detection?

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#114]
There are multiple aimbots in existence for JK3, this is a confirmed fact. There have been accusations recently of some people using aimbots.

Here's an old video of one....
https://www.youtube.com/watch?v=sK5H3NSIJxY

I don't know how the aimbots work, but is there a way to detect them?

I know Eyen made one of the aimbots. If we figured out how it works, maybe we could detect it?

**Comment by deathsythe47** [comment]
inb4 spec the guy, record demos, use openjk autodemo, etc....

**Comment by dpadgett** [comment]
spawn invisible enemies circling around them and see if they spin out of control?

**Comment by deathsythe47** [comment]
Meh, probably impossible
