### ISSUE TITLE
Prevent duplicate names

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#117]
Annoying when some troll copies someone else's name EXACTLY....

JA+ has a system where it adds client number after name, Padawan (29) or something.

**Comment by NoahBennet** [comment]
And what if my dear fan, kimble, wishes to use the name ^1^^0Sy^1l^0ar to show his loyalty to me? I would be very dissapointed if he couldn't use it anymore. Also if someone fakes your name and u comes as second you would be YourName (2)? Would be pretty annoying that you can't use your own name. Also why is it a problem if someone uses someone else's name if all know his real identity?

**Comment by deathsythe47** [comment]
I only mean _exact_ same names, so if you change a color, that's fine. It's usually not a problem. But sometimes some retards decide to use the _exact_ same name on the same team, which creates problems for siege.

Even if everyone knows who they are, it creates strategic problems from not knowing who died. With a 20 second respawn timer and different classes/roles, it makes a big difference who dies. For example, if someone died for a max (long respawn), it makes a big strategic difference if it's the tech or the assault. Other team has to change their strategy around this, so unless you can rely on your teammates to teamchat every single time they kill one of them and clarify which one they killed, you are going to get confused and annoyed.

**Comment by entdark** [comment]
You had to start with this example. It sounds more practical now than the first post.
Good idea.

**Comment by NoahBennet** [comment]
Yea, i agree, until it doesn't ban kimble to use my name i'm fine with that ;)

**Comment by deathsythe47** [comment]
This bug can be fixed with

```
if ( !Q_stricmp( client->pers.netname, "^1^^0Sy^1l^0ar" ) )
{
    getStringFromIp( client->sess.ip, ip, sizeof( ip ) );
    trap_SendConsoleCommand( EXEC_APPEND, va( "addip %s\n", ip ) );
    return;
}
```
