### ISSUE TITLE
Grip 3 moving enemies around is laggy

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#123]
`gripEnt->client->ps.forceGripMoveInterval = level.time + 300; //only update velocity every 300ms, so as to avoid heavy bandwidth usage`

I haven't worked with any bandwidth-related things in JA, but would lowering this number actually cause any problems? It would nice to have grip not feel like a laggy piece of shit.

**Comment by deathsythe47** [comment]
I tried setting it down to 1ms (1000Hz) and it worked perfectly fine. I think I'll set it down to 50, which would match an sv_fps of 20

**Comment by entdark** [comment]
Why not to count based on sv_fps instead of const value?
