### ISSUE TITLE
"vid_restart" when spectating or being piloting person (e.g. in ATST)

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#15]
When doing /vid_restart command when spectating person that is inside vehicle such as ATST (or just being by itself pilot), client gets bugged and sees seekerdrone around, and camera is messed up.

**Comment by deathsythe47** [comment]
I'm not sure this has anything to do with vid_restart. I just launched JA, joined server, got into ATST, and when I got out, I had the bug.

Didn't do any vid restarts, and I still got the bug.

**Comment by TheSil** [comment]
Well it is one way to reprodue the bug. But of course there might another triggering event, or it might even be different bug. Anyway I actually think that this is a client side bug, because others do not see what you see.

**Comment by TheSil** [comment]
Alright figured out the root cause... 

Problem is that when client is in piloted vehicle (like ATST), server engine is trying to save some bandwidth by not sending certain information over the network:

```
    {//pilot riding *inside* a vehicle!
        MSG_WriteBits( msg, 1, 1 ); // Pilot player state
        numFields = (int)ARRAY_LEN( pilotPlayerStateFields ) - 82;
        PSFields = pilotPlayerStateFields;
```

Here last 82 parameters are not transmitted. Unfortunately one of these parameters is genericEnemyIndex, which when not transmitted is interpreted as 0 (but in reality it is -1). Then client is taking this 0 and working with it, which creates seeker drone around the player. Other view problems that are part of this bug are probably just caused by some another field that is not being sent over network as well.

Solution would be to just remove this limitation in server engine (in todays network bandwidths, this should not be issue at all). I have tried to removed the "-82" and it works. I will try to come up with engine hack inside base_enhanced for vanilla engine users...

Btw this also explains why you encountered this problem without vid_restart. This bug will be triggered anytime the uncompressed frame is sent to the client from the server. This can happen for example if you are lagged for too long. So, in theory, getting into ATST, simulating connection interrupted for some time, and then getting of the ATST, should cause the bug as well.
