### ISSUE TITLE
Player gets stuck when respawning into the shield

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#17]
Player gets stuck when respawning into the shield, even though it is his team shield in which case it should be disabled (made non solid).

**Comment by TheSil** [comment]
See ee6be3f for fix.

**Comment by deathsythe47** [comment]
This actually seems to still be bugged. I would reopen this issue.
Sith recorded this video from the new build yesterday:
https://www.dropbox.com/s/wdd93hu3ufqz7eq/jka.rar?dl=0

There are two videos in the rar -- ignore the lift kill one

**Comment by TheSil** [comment]
Yea i think its because the fix is taking only allies into account. That is easy because all you need to do is just disable shield. 

But what would be expected behaviour when player spawns into enemy shield (which is what i think happened on the video)? One might say just moving him outside the shield, but that way you have to calculate trajectories and find place where to move the player safely, which gets tricky.

**Comment by TheSil** [comment]
But thinking about it, i think we might just try to let player move through the shield when he is already in it. Although im not sure if that is any less tricky :D.

**Comment by deathsythe47** [comment]
I think just disable the shield until the player moves away from it. Even if it's an enemy shield.

It's very rare that this happens with _enemy_ shields. In the event that it does, though, the player shouldn't get stuck.

By the way, the same thing applies to NPCs. You can lay a shield at the ATST spawn and when it respawns, you can get in it, but you can't move it until the shield dies.

**Comment by TheSil** [comment]
Possibly fixed (not including the NPC part though), but needs to be tested.

**Comment by TheSil** [comment]
Try this, and confirm if it works.
