### ISSUE TITLE
Team chat is visible to all players during round countdown in siege

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#34]
Currently when round is being restarted in siege, all players are technically in spectators. This causes team chat to be shared between all players, even though the teams are practically already selected and game begins. This often leads to non wanted information being shared with the other team.

**Comment by deathsythe47** [comment]
fix 0ba70e361b85dbed40e795efa6ca89e9f493c4e6

**Comment by TheSil** [comment]
Inspired by your fix, but moved it to different place where it should fit more.
