### ISSUE TITLE
Floating items bug

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#39]
phil: floating siege items bug
phil: like if you have codes/crystal
phil: if you die next to a wall, the item starts to float up the wall
phil: really annoying, like if someone dies next to a wall and it floats up, if you are a gunner(no force jump) you can't get it
phil: very easy to test, just grab codes and /kill next to a wall

**Comment by deathsythe47** [comment]
This bug is annoying on most maps, but is desirable for korriban(it has been considered a strategy for many years), so may be best to use sv_floatingitems cvar (default to 0) and using per-map cfg system, server owner can optionally enable it for some maps.
