### ISSUE TITLE
Siege respawn timer does not respawn players that did not use mouse1 click

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#43]
When player dies shortly before siege respawn timer hits, he needs to perform mouse1 click to get respawned. Respawning should be independent on this.

**Comment by TheSil** [comment]
Partially implemented in 438e8f52384bef9e42bcc0f377c54dcecf1996f0. However delay was removed, but it should be returned.

**Comment by deathsythe47** [comment]
Basically, the "without click" delay should be changed to match the "with click" delay.
