### ISSUE TITLE
Spectators cannot see HP of breakable objects

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#51]
If you are in spec and you move your mouse over a breakable object (turret, siege objective, emplaced gun, NPC, etc.) you cannot see the little bar showing its health.

**Comment by deathsythe47** [comment]
As a side note, it would be nice to also see HP(and armor) bars for _players_ from spec

**Comment by TheSil** [comment]
This is actually client side thing and is intented. It can be modified easily by removing

if ( cg.snap->ps.persistant[PERS_TEAM] != TEAM_SPECTATOR )

condition in function void CG_ScanForCrosshairEntity( void ) (content within {} brackets should remain, just the condition should not be evaluated and body of the if shoudl be always executed).
