### ISSUE TITLE
Spectators do not see/hear "objective complete" messages or sounds

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#52]
Only people ingame hear these sounds and see these messages.

**Comment by TheSil** [comment]
This is actually client side bug, can be fixed in CG_SiegeObjectiveCompleted() method by removing

```
if ( myTeam == TEAM_SPECTATOR )
{
    return;
}
```

**Comment by entdark** [comment]
Oh, thanks, I will use.
