### ISSUE TITLE
Siege objectives should score 100 points

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#58]
Currently they score 20 points, which is an arbitrary/meaningless/stupid number. It seems this was meant to give players a sense of "score" in a large public server, so people focusing on objs could feel important, but it would be much more useful to have 100 point scores. That way you could look at a player and see how many objs and kills he has.

Like if I have 215 points -- 2 obj and 15 kills, simple.

But in base I would have 55 points, WTF? Is that 2 obj and 15 points? Or 3 obj and -5 points? Or 1 obj and 35 points? Why do I have to do math?

**Comment by dpadgett** [comment]
or is 215 1 obj and 115 kills?

**Comment by Grab11** [comment]
...or separate objectives and kills in score board -smod

**Comment by deathsythe47** [comment]
@dpadgett nobody gets 115 kills, there is no room for confusion; even if you got 4kpm for 20 minute straight(ridiculously impossible) that would still be only 80 kills
@Grab11 not a bad idea but would probably require awarding _no_ points to people, and people without smod wouldn't be able to see

**Comment by deathsythe47** [comment]
Sent pull request 2c3d87f6a6de8b8b50e38e8e8efbf0ccf20e648d

This code is so weird. So if you capture any obj, you get 20 points....unless it's the final obj, which gives you 30 points. But everyone on the team gets 10 points for the final obj, _including_ the guy who captured it. So the guy who captured the final obj actually gets 40 points. Also if defense holds for 20 minutes, they all get 10 points.

WTF is all this shit. Just make a simple 100 pts for all objs, only for the guy who got obj.

**Comment by entdark** [comment]
Such things have to be optional, some prefer the original behavior. The best solution is to read the custom behaviour from some config files. The mod just has to provide such an interface, the rest is the users' business.

**Comment by deathsythe47** [comment]
I understand that on principle. But I think a cvar would be nice because the original method makes no sense. I doubt you could find one active sieger who would say that the 20/30/10 system is more logical/helpful than a simple 100 system.
