### ISSUE TITLE
Item death timer keeps running during /pause; item then dies on /unpause

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#65]
For example sentries always die after 60 seconds in jk3.

Currently if you use a sentry and then /pause the game for like 90 seconds and then /unpause the game, it will instantly blow up.

**Comment by TheSil** [comment]
Unfortunately because of how pause works, this needs to be fixed specifically for each timer. I've fixed this for sentry, are there any other items you are aware of that are still a problem?

**Comment by deathsythe47** [comment]
I only tested it for sentry when I submitted this issue, but I can test for some other items later. I would imagine it's the same.

**Comment by entdark** [comment]
How about to add some generic function in gentity_t scope that always gets called on pause? So it works for all the kind of entities. o:

**Comment by TheSil** [comment]
Yea something like pausedthink instead of regular think, that could work.
