### ISSUE TITLE
Disparity between apparent and actual full charge for determination of incineration effect

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#66]
When you charge a disruptor rifle, it plays the charging sound and shows the meter filling up for 1.5 seconds. When the sound ends and the meter is full, your rifle is fully charged, right?

Wrong!

Wrong in siege, anyway. In siege, it takes 5 seconds for it to ACTUALLY fully charge. In siege, the maximum charge is 200, whereas in other gametypes it is 60. You charge 40charge per second, and your damage dealt is equal to 70 + your charge level. Meaning you do a LOT of damage when you sit there charging for 5 seconds -- up to a whopping 270 damage -- compared with charging for 1.5 seconds, which only does 130 damage.

The developer comments that they wanted to increase damage for siege:

```
maxCount = 60;
if ( g_gametype.integer == GT_SIEGE )
{
     maxCount = 200; //maybe a full alt-charge should be a *bit* more dangerous in Siege mode?
}
```

Personally, I think the developer actually intended for a charge _of the same length_ to deal more damage, rather than allowing for _longer charges than the meter indicates_. I think they didn't fully test the code. But that's just my opinion, and in 2015 we probably shouldn't be screwing with damage.

In any case, though, the bug here is that the detection of whether or not to incinerate the player (cool orange disintegration effect) is based on whether or not you are "fully charged" -- which in siege means you will only ever see the incineration effect if you have charged your rifle for a full 5 seconds. I think it is safe to say that this is an oversight by the developer, and that you should see the disintegration effect happen after the charge-meter fills up and the sound finishes -- NOT after a ridiculous 5-second-long mega-charge.

Line 885 of g_weapon.c reads:

```
                if (traceEnt->client && preHealth > 0 && traceEnt->health <= 0 && fullCharge &&
```

it should read:

```
                if (traceEnt->client && preHealth > 0 && traceEnt->health <= 0 && count >= 60 &&
```

Again, this bug is just about the visual effect, not the damage

**Comment by entdark** [comment]
Sounds like client side bug that needs some more conditions for siege charger.

**Comment by TheSil** [comment]
Well at first it looks like client side bug after more invetigation it seems just like you say, they didnt really test it, it takes too long, it does not drain ammo after the 1.5 second delay that is usual, etc.. So this feature could be finished, that would need changes on both client and server side, or we could just remove it from server (client does not support it anyway). This would be simply done by removing this from WP_DisruptorAltFire() :

```
    if ( g_gametype.integer == GT_SIEGE )
    {//maybe a full alt-charge should be a *bit* more dangerous in Siege mode?
        maxCount = 200;//the previous line ALWAYS evaluated to 135 - was that on purpose?
    }
```
