### ISSUE TITLE
Seeker drone targets ATST

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#67]
However it shouldn't be prevented from attacking ALL vehicles, because it can actually hurt some, which is good. It can hurt swoops, or even the swoop pilot who is visible to the player.

There needs to be some method of filtering which vehicles are eligible to shoot at, and which aren't. Could simple, like simply ignoring vehicle type VH_WALKER

**Comment by TheSil** [comment]
Is this actually a bug? I mean ATST is enemy to the seeker drone, so it makes sense it shoots at it. Its inability to hurt it is another problem. I think this would make seeker drone a little bit too inteligent than it is supposed to be.

**Comment by deathsythe47** [comment]
I think if seeker drone is intelligent enough to distinguish enemies from allies, it should be intelligent enough to distinguish ATSTs from humanoids

**Comment by entdark** [comment]
I see no problem too, ATST is an enemy. None said that seeker has to shoot humanoids only.

**Comment by deathsythe47** [comment]
I don't see how a seeker could have the intelligence to detect if someone harbors in their heart an allegiance to a particular political organization, yet not have the intelligence to recognize a 9-meter tall machine.

**Comment by entdark** [comment]
It recognizes and shoots. Works as intended.

**Comment by deathsythe47** [comment]
So you're saying that the designer of seeker drones created a system of artificial intelligence, 3d optic sensors, pheromone-sensing/mind-reading technology so sophisticated that it could designate potential targets as friend/foe _based on their political allegiance with 100% accuracy_, even if they are completely hidden inside a vehicle(the seeker is targeting the pilot, not the vehicle), but not sophisticated enough to filter out targets it cannot damage?

Should a seeker drone deployed by a Rebel shoot at the Death Star, too?

**Comment by entdark** [comment]
No.
No.

**Comment by deathsythe47** [comment]
gg

**Comment by deathsythe47** [comment]
Fixed 49c67630dcb00579a7074e28fbb670cb69e5da1f
