### ISSUE TITLE
Bug with rancor grabbing player immediately before player dies

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#68]
If rancor grabs a player (with the intention of eating him) _immediately_ before the player dies, the player will die again from being eaten by the rancor a few seconds later, even though he has already died.

For example, if I get grabbed by the rancor 1 second before the spawn and then _immediately_ selfkill and respawn, a few seconds later I still get "eaten" by the rancor and killed, even if I'm 50 kilometers away.

**Comment by TheSil** [comment]
This is just tempoary fix, not allowing player to respawn when is being eaten. But I think it would be nice to allow player to respawn, just make it properly, leave rancor with just dead body to eat, and do not affect original player.

**Comment by deathsythe47** [comment]
I personally think this fix is good actually. IMO you shouldn't be able to get out of being killed by the rancor by SKing...you should be punished

But that's just my opinion, and either way is better than the original bug, anyway.

I implemented your approach in my fork

**Comment by Grab11** [comment]
IMO you shouldn't be able to get out of being killed by the rancor by SKing...you should be punished
^this
