### ISSUE TITLE
Seeker and sentry continue trying to attack players who have disconnected

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#71]
Example:

Join game
Add bot to opposite team
Deploy sentry/seeker
Sentry/seeker starts shooting at bot
Kick bot
Sentry/seeker continues to shoot at the empty space that was previously occupied by the bot

It should be noted that if you deploy your item _after the player has already left_, a sentry will **not** begin attacking the empty space, but a seeker **will** begin attacking the empty space (at least in my testing)

**Comment by TheSil** [comment]
Fixed in 86ff86cda6bf03156f99c5daea777fc8e16d0703, tested for seeker only. Would be cool to test for sentry also.
