### ISSUE TITLE
Changing class in siege causes body to stuck in "jesus star" pose until respawned

### ISSUE THREAD

**Issue by TheSil** [TheSil/base_enhanced#74]
Change teams AND siege class while being alive in game and you will see your character getting stucked with hands and legs straight, instead of just seeing regular dying.

**Comment by TheSil** [comment]
![image](https://cloud.githubusercontent.com/assets/1452077/9424192/36d06832-48e3-11e5-8032-4eb1f43be10b.png)

**Comment by entdark** [comment]
lol @ naming it "jesus" pos.
Called "star" actually.

**Comment by TheSil** [comment]
:D should rename it to jesus star perhaps then?

**Comment by Grab11** [comment]
It's more like vitruvian man. It happens after leaving body after dying.

**Comment by TheSil** [comment]
Anyway managed to fix this, appear to be in client mod though. Following lines of code cause it:

```
cg_entities[clientNum].currentState.legsAnim = 0;
```

and

```
cg_entities[clientNum].currentState.torsoAnim = 0;
```

in CG_NewClientInfo() in cg_players.c. Simply removing them seems to resolve the issue and so far i havent observed any side effects.

**Comment by entdark** [comment]
Plz, test more, I want to steal the proper fix.
