### ISSUE TITLE
Finishing siege round with saber causes sound bug when teams swap

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#75]
Example:

Select jedi class (lightsaber)
Complete final objective in a siege map
At intermission, when the teams switch on the scoreboard, you hear lightsaber sound

**Comment by TheSil** [comment]
Fixed this on client side, in CG_CheckPlayerG2Weapons() by adding (ps->pm_type != PM_INTERMISSION) condition for saber sound.
