### ISSUE TITLE
Cvar so you can't hear enemy voice chats

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#79]
Siege has a voice chat menu like counterstrike, with some things like:
- "Medic"
- "I need assistance"
- "Sniper"
- "Roger"
- etc

However, unlike Counterstrike, due to an unfortunate, dumb decision by Ravensoft, you can hear enemy voice chat sounds if you are close, even though you can't see the text. This effectively renders voice chat useless, because if the enemy can hear it, then you should just use teamchat instead because it's private. I have personally never used voice chat for this reason, and I always tell people never to use it.

For example, if I hear an enemy use a "medic" bind and move toward his tech(obviously to get healed), I know I have an easy kill if I focus on him. Or if I hear a secondary jedi spam "roger" I know he is telling his teammate that he is going to wait by the next obj to rush, so I should retreat to counter this.

I think you can see a little icon over the guy's head, too.

**Comment by entdark** [comment]
Should be handled by client-side. Works fine and none complained about it in CTF. Personal stuff -> client-side.

**Comment by deathsythe47** [comment]
Is it possible to prevent server from sending the data to enemies?

**Comment by Grab11** [comment]
It's voice not message. Characters say that so everyone can hear it. Removing it is like removing taunt or pain sounds.

**Comment by deathsythe47** [comment]
It's not like that at all, because you can't hear taunt and pain sounds from 99999km away. You can hear these messages from anywhere if you're on the same team, but only close up if you're an enemy.

**Comment by entdark** [comment]
I confirm that voice chat commands from teammates are local sounds.
And seems like your request is client-side only anyways.

**Comment by deathsythe47** [comment]
Once again, not clientside.

https://github.com/deathsythe47/base_entranced/commit/974b23a4a2a893d78eec423afc90467c225af7a1
