### ISSUE TITLE
Players can move through laser mines without explosion

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#80]
Place a laser mine on the side of a box low off the ground( 10cm from ground or something) and roll through it. The mine doesn't blow up even though your guy went directly through the laser.

**Comment by Grab11** [comment]
Lol, look at this demo from yesterday:
https://www.dropbox.com/s/0m3ajn2u47z7wtl/wtfmines.dm_26?dl=0

**Comment by deathsythe47** [comment]
Wow, that video shows the bug is worse than I thought.
