### ISSUE TITLE
Option to hide location from teamchat if you're spec

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#81]
If you are spec, nobody really cares where you're looking around. You are probably just having a conversation with other specs, but often your screen is blocked by many messages like >Hangar Door Control Room< after your name, which is unnecessary.

**Comment by deathsythe47** [comment]
ed301375b33df664cf3bf7662e3068b30e288a9c

**Comment by deathsythe47** [comment]
Further testing shows that above fix also hides location while you're in post-death temporary spec mode in siege. Needs more work.

**Comment by deathsythe47** [comment]
Nevermind, more testing shows that was some other code I was trying out.

**Comment by entdark** [comment]
Should be client-side. You are doing it all wrong. :S

**Comment by deathsythe47** [comment]
umad
