### ISSUE TITLE
Shields can die even while you are standing on them if they are old enough

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#82]
If you stand on a shield, it is supposed to stop it from decaying, right? Well if you stand on a shield for a _very_ long time (one test I did took 8 minutes!!) it can still deactivate (idk if this happens every time or only sometimes). You hear the sound and everything, even though you are standing on the shield.

I don't know if this is a bug, or the game is actually intentionally _decaying shields very slowly_ while you are standing on them(as opposed to _not decaying at all_).

**Comment by TheSil** [comment]
Checked this and it is intentional, 1 point damage every 200 milliseconds, from the overall 2000 health for siege, it should decay in about 400 seconds = 6.67 minutes.

**Comment by TheSil** [comment]
One more clarification to this, it also depends on sv_fps. For example for sv_fps 30, server executes on 33ms period, so the 200 ms period actually becomes 231 (7*33), so instead of intented 400 seconds this become 462 seconds, or 7.7 minutes, which is more close to what you observed.
