### ISSUE TITLE
Healing NPCs doesn't work

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#84]
You should be able to heal some NPCs in siege. For example, in hoth, the walker has these keys set:

```
healingrate 250

healingclass Imperial Tech

healingsound sound/ambience/doomgiver/doom_bridge.wav
```

These should allow you to heal it if you have the right siege class. However, it doesn't work. Press +use on it and nothing happens. Ravensoft put in these keys with the intention that you could heal the walker, but they didn't properly code the game so that you could actually do it.

Also, the R5D2 droid has the same lines(for defense tech) and it also cannot be healed.

If you used the same keys for a func_breakable, it would work. For example, the consoles in the command center can be healed by defense tech, and they use the same keys (healingrate, healingclass, healingsound...)

**Comment by TheSil** [comment]
Check the referenced commit, it should work for vehicles. With R5D2 there is a non game code related problem, but rather map related one. There is

```
"healingrate" "250"
"healingclass" "Rebel Light Tech"
```

set for R5D2, but problem is the class name is supposed to be "Rebel Tech", hence it cannot work.

**Comment by deathsythe47** [comment]
Is it possible to fix it for non-vehicle NPCs too?

**Comment by TheSil** [comment]
Any example where it does not work? There was a bug specific to vehicles.

**Comment by deathsythe47** [comment]
The R5D2 you mentioned, while there is indeed a map bug, even if you fixed it to be "Rebel Tech" it still doesn't work due to game code bug also.
