### ISSUE TITLE
Sentry can't target properly

### ISSUE THREAD

**Issue by Grab11** [TheSil/base_enhanced#87]
Everything is here:
http://imgur.com/a/b9WJB
Also when there is body between sentry and enemy.

**Comment by deathsythe47** [comment]
What were the exact steps you did to reproduce this?

Also where did you get that font for drawtimer, team overlay, fps?

**Comment by Grab11** [comment]
Nothing special, just enemy sentry placed on floor. I just stand behind something. Add me on steam głupi.

**Comment by TheSil** [comment]
Updated to take viewheight into account. It is not perfect but i think it is good enough.
