### ISSUE TITLE
/tell sucks

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#89]
You have to type in someone's client number in order to send a message. People should be able to /tell messages by typing in a partial client name.

**Comment by entdark** [comment]
Sil pampered us w/ smod and his wisperer. x] So everyone forgot about tell command.
I agree that this should be done anyways.

**Comment by deathsythe47** [comment]
Yeah it is often a lot easier to just really quickly type /tell pada join red than to use sm_whisp, find the name in the list, click on it, click on the message bar (this usually results in accidentally closing sm_whisp 2-3 times), type message, and hit send (this usually results in accidentally closing sm_whisp 2-3 times also)

**Comment by entdark** [comment]
Type in the public chat lol

**Comment by deathsythe47** [comment]
Btw on a related note, it would be helpful to have a universally usable function that can find a player when given a partial match of their name without colors, like with whois. With whois I can just type /whois guy and find a player named guy019238317214 with crazy colors. Or I can optionally type client number and it will find the guy also.

This function could be added to many other commands, for example forceteam. You should just be able to type forceteam gra r and it would forceteam grab to red. Or if there are two grabs, you could still use client number.

callvote kick, forceteam, tell, etc.... this would be useful for many commands

**Comment by deathsythe47** [comment]
a73311e30530e0bec3909675c888ad7bf5a9876f

Also did similar for forceteam 491da996755055538e419895d51261c6cc487329
