### ISSUE TITLE
Bryar pistol animations are bugged

### ISSUE THREAD

**Issue by deathsythe47** [TheSil/base_enhanced#96]
Obviously this weapon was phased out from JK2 and mostly replaced by the DL-44 pistol, but you can still use this gun in JK3, through pickups on custom maps, custom siege classes, cheats, etc.

The animation bugged, though, it's just the standing animation. It should use the same animations as the DL-44.

Obviously client-related.

**Comment by Grab11** [comment]
I wanted to report this first :( 
We need 1 big issue for client side enhancements/bugs.

**Comment by entdark** [comment]
Why to post client-side issues on server-side mod repository?

**Comment by deathsythe47** [comment]
Sorry, I'll post them in the future to https://github.com/TheSil/smod/

oh wait

**Comment by entdark** [comment]
Just do not post.

**Comment by deathsythe47** [comment]
Some of them end up being related to server, like https://github.com/TheSil/base_enhanced/issues/93 and people can help offer their input on github. Sil has posted client issues here before. Furthermore this isn't some gigantic project with hundreds of open issues. Chill out, I don't know what your problem is.

**Comment by deathsythe47** [comment]
It's better now, but your guy lowers his bryar between every shot.

**Comment by TheSil** [comment]
Thats caused by client prediction. Try newest smod, with that i dont see any issue.
